#!/bin/bash

echo export GITHUB_USERNAME=
echo export GITHUB_ORGANIZATION=
echo export GITHUB_LOCAL_PATH=
echo export GITHUB_ACCESS_TOKEN=

echo export BITBUCKET_OAUTH_TOKEN=
echo export BITBUCKET_OAUTH_TOKEN_SECRET=
echo export BITBUCKET_ORGANIZATION=
echo export BITBUCKET_LOCAL_PATH=
