#!/bin/bash

export GITHUB_USERNAME=
export GITHUB_ORGANIZATION=
export GITHUB_LOCAL_PATH=
export GITHUB_ACCESS_TOKEN=

export BITBUCKET_CONSUMER_KEY=
export BITBUCKET_CONSUMER_SECRET=
export BITBUCKET_OAUTH_TOKEN=
export BITBUCKET_OAUTH_TOKEN_SECRET=
export BITBUCKET_ORGANIZATION=
export BITBUCKET_LOCAL_PATH=
